# Generated by Django 4.0.5 on 2022-07-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
    ]
