# Generated by Django 4.0.5 on 2022-07-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_city_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='slug',
            new_name='city_slug',
        ),
    ]
