# Generated by Django 4.0.5 on 2022-07-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_rename_slug_city_city_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
    ]
